---
title: 'Four Marker Overview — All Patients'
author: 'Tazein Shah, Vaidehi Gupta'
date: "06-10-2026"
output:
  pdf_document:
    toc: true
editor_options:
  markdown:
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE,
                      fig.width = 14, fig.height = 10)
```

## Overview

Mask overlays for DNA191, EpCAM, CD68, and SMA across all patients (p10–p20).

---

## 1. Load Libraries

```{r libraries}
.libPaths(c("/restricted/projectnb/camplab/home/vgupta7/R_libs", .libPaths()))

library(imcRtools)
library(cytomapper)
library(tidyverse)
```

---

## 2. Define Paths

```{r paths}
base_path <- "/restricted/projectnb/camplab/projects/20220504_Suzuki_LN/TumorIMC/steinbock"

patient_dirs <- list(
  p10  = file.path(base_path, "p10_results"),
  p11  = file.path(base_path, "p11_results"),
  p12  = file.path(base_path, "p12_results"),
  p13  = file.path(base_path, "p13_results"),
  p14  = file.path(base_path, "p14_results"),
  p15  = file.path(base_path, "p15_results"),
  p16  = file.path(base_path, "p16_results"),
  p17  = file.path(base_path, "p17_results"),
  p18  = file.path(base_path, "p18_results"),
  p19  = file.path(base_path, "p19_results"),
  p20a = file.path(base_path, "p20_4_25_results"),
  p20b = file.path(base_path, "p20_5_19_results")
)

panel         <- read.csv(file.path(base_path, "panel.csv"))
kept_channels <- panel$name[panel$keep == 1]
```

---

## 3. Helper Functions

```{r helpers}
load_and_norm <- function(pt_path) {
  images <- loadImages(file.path(pt_path, "img/"))
  masks  <- loadImages(file.path(pt_path, "masks_deepcell/"), as.is = TRUE)

  channelNames(images) <- kept_channels

  mcols(images)$sample_id <- names(images)
  mcols(masks)$sample_id  <- names(masks)

  images_norm <- cytomapper::normalize(images, separateImages = TRUE)
  images_norm <- cytomapper::normalize(images_norm, inputRange = c(0, 0.2))

  list(images_norm = images_norm, masks = masks)
}

plot_mask <- function(images_norm, masks, colour_by, colour) {
  img_ids <- seq_len(length(images_norm))
  plotPixels(
    images_norm[img_ids],
    mask           = masks[img_ids],
    img_id         = "sample_id",
    missing_colour = "white",
    colour_by      = colour_by,
    colour         = colour,
    image_title    = list(position = "topleft", cex = 1),
    legend         = list(colour_by.title.cex = 0.8, colour_by.labels.cex = 0.8)
  )
}
```

---

## 4. Plots

```{r all-patients, fig.height=12}
figures_dir <- "/restricted/projectnb/camplab/projects/20220504_Suzuki_LN/TumorIMC/analysis/figures/cellseg"
dir.create(figures_dir, showWarnings = FALSE)

for (pt_name in names(patient_dirs)) {
  cat("Loading:", pt_name, "\n")
  dat <- load_and_norm(patient_dirs[[pt_name]])

  # Save to file
  png(file.path(figures_dir, paste0("cellseg_", pt_name, ".png")),
      width = 14, height = 12, units = "in", res = 300)
  
  plot_mask(dat$images_norm, dat$masks,
    colour_by = c("DNA191", "EpCAM", "CD68", "SMA"),
    colour    = list(DNA191 = c("black", "blue"),
                     EpCAM  = c("black", "green"),
                     CD68   = c("black", "yellow"),
                     SMA    = c("black", "red")))
  
  dev.off()
  
  # Also display in Rmd
  plot_mask(dat$images_norm, dat$masks,
    colour_by = c("DNA191", "EpCAM", "CD68", "SMA"),
    colour    = list(DNA191 = c("black", "blue"),
                     EpCAM  = c("black", "green"),
                     CD68   = c("black", "yellow"),
                     SMA    = c("black", "red")))
}
```

---

## Session Info

```{r session-info}
sessionInfo()
```